#!/usr/bin/env php
<?php
/**
 * @author HealthwareIntl | Carmine Rumma
 *
 */

set_time_limit(0);

$cwd = empty($_SERVER['PWD']) ? getcwd() : $_SERVER['PWD'];
require_once (dirname(__FILE__) . "/autoload.php");
require_once (dirname(__FILE__) . "/bootstrap.php");
$command = "";
$opt = array();
if (isset($argv[1])){
    $command = $argv[1];
    $opt = explode(":", $command);
}

if (!empty($opt[1])) {
    $command = $opt[0];
}

\hcore\cli\HCli::getInstance()->run($command, $opt, $argv);
